### ISSUE TITLE
compile error : value %:% is not a member of breeze.linalg.Vector[Double]

### ISSUE THREAD

**Issue by moranrr** [byzer-org/byzer-lang#1012]
When I compile with spark2.3, 
use ``mvn clean package -Pshade  -DskipTests  -pl streamingpro-mlsql -am   -Pscala-2.11 -Ponline -Phive-thrift-server -Pcarbondata  -Pcrawler -Pdsl -Pxgboost -Pspark-2.3.0 -Pstreamingpro-spark-2.3.0-adaptor``

I get the following error：
```
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:150: error: value *:* is not a member of breeze.linalg.Vector[Double]
[INFO]       (vec1.asBreeze *:* vec2.asBreeze).fromBreeze
[INFO]                      ^
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:157: error: value +:+ is not a member of breeze.linalg.Vector[Double]
[INFO]       (vec1.asBreeze +:+ vec2.asBreeze).fromBreeze
[INFO]                      ^
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:164: error: value -:- is not a member of breeze.linalg.Vector[Double]
[INFO]       (vec1.asBreeze -:- vec2.asBreeze).fromBreeze
[INFO]                      ^
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:171: error: value %:% is not a member of breeze.linalg.Vector[Double]
[INFO]       (vec1.asBreeze %:% vec2.asBreeze).fromBreeze
[INFO]                      ^
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:200: error: ambiguous implicit values:
[INFO]  both method mapUFuncImpl in object Vector of type [Tag, V, U](implicit impl: breeze.generic.UFunc.UImpl[Tag,V,U], implicit canMapValues: breeze.linalg.support.CanMapValues[breeze.linalg.Vector[V],V,U,breeze.linalg.Vector[U]])breeze.generic.UFunc.UImpl[Tag,breeze.linalg.Vector[V],breeze.linalg.Vector[U]]
[INFO]  and method fromLowOrderCanMapValues in trait MappingUFunc of type [T, V, V2, U](implicit handhold: breeze.linalg.support.CanMapValues.HandHold[T,V], implicit impl: breeze.numerics.package.ceil.Impl[V,V2], implicit canMapValues: breeze.linalg.support.CanMapValues[T,V,V2,U])breeze.numerics.package.ceil.Impl[T,U]
[INFO]  match expected type breeze.numerics.ceil.Impl[breeze.linalg.Vector[Double],VR]
[INFO]       ceil(vec1.asBreeze).fromBreeze
[INFO]           ^
[ERROR] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\core\compositor\spark\udf\Functions.scala:270: error: ambiguous implicit values:
[INFO]  both method mapUFuncImpl in object Vector of type [Tag, V, U](implicit impl: breeze.generic.UFunc.UImpl[Tag,V,U], implicit canMapValues: breeze.linalg.support.CanMapValues[breeze.linalg.Vector[V],V,U,breeze.linalg.Vector[U]])breeze.generic.UFunc.UImpl[Tag,breeze.linalg.Vector[V],breeze.linalg.Vector[U]]
[INFO]  and method fromLowOrderCanMapValues in trait MappingUFunc of type [T, V, V2, U](implicit handhold: breeze.linalg.support.CanMapValues.HandHold[T,V], implicit impl: breeze.numerics.package.floor.Impl[V,V2], implicit canMapValues: breeze.linalg.support.CanMapValues[T,V,V2,U])breeze.numerics.package.floor.Impl[T,U]
[INFO]  match expected type breeze.numerics.floor.Impl[breeze.linalg.Vector[Double],VR]
[INFO]       floor(vec1.asBreeze).fromBreeze
[INFO]            ^
[WARNING] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\dsl\mmlib\algs\SQLPythonFunc.scala:70: warning: non-variable type argument String in type pattern Iterator[String] (the underlying of Iterator[String]) is unchecked since it is eliminated by erasure
[INFO]         case a: Iterator[String] => recordMultiLineLog(kafkaParam, line.asInstanceOf[Iterator[String]], logCallback)
[INFO]                 ^
[WARNING] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\dsl\mmlib\algs\SQLStandardScaler.scala:24: warning: imported `feature' is permanently hidden by definition of package feature in package algs
[INFO] import org.apache.spark.mllib.feature
[INFO]                               ^
[WARNING] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\udf\ScalaRuntimeCompileUDF.scala:58: warning: abstract type reflect.runtime.universe.DefDef is unchecked since it is eliminated by erasure
[INFO]     val checkResult = typeCheckResult.isInstanceOf[DefDef] || typeCheckResult.isInstanceOf[ClassDef]
[INFO]                                                   ^
[WARNING] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\udf\ScalaRuntimeCompileUDF.scala:58: warning: abstract type reflect.runtime.universe.ClassDef is unchecked since it is eliminated by erasure
[INFO]     val checkResult = typeCheckResult.isInstanceOf[DefDef] || typeCheckResult.isInstanceOf[ClassDef]
[INFO]                                                                                           ^
[WARNING] E:\sources\streamingpro\streamingpro-mlsql\src\main\java\streaming\udf\ScalaRuntimeCompileUDF.scala:99: warning: abstract type reflect.runtime.universe.DefDef is unchecked since it is eliminated by erasure
[INFO]       .filter(_.isInstanceOf[DefDef])
[INFO]                             ^
[WARNING] 9 warnings found
[ERROR] 6 errors found

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] StreamingPro Parent POM ............................ SUCCESS [ 11.655 s]
[INFO] streamingpro-jython ................................ SUCCESS [ 13.674 s]
[INFO] streamingpro-common ................................ SUCCESS [ 47.165 s]
[INFO] streamingpro-spark-common .......................... SUCCESS [ 46.859 s]
[INFO] streamingpro-api ................................... SUCCESS [ 40.770 s]
[INFO] streamingpro-spark-2.3.0-adaptor ................... SUCCESS [01:07 min]
[INFO] streamingpro-dsl ................................... SUCCESS [ 11.286 s]
[INFO] streamingpro-crawler ............................... SUCCESS [01:09 min]
[INFO] streamingpro-xgboost ............................... SUCCESS [ 27.316 s]
[INFO] streamingpro-mlsql-spark_2.3 ....................... FAILURE [01:03 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:43 min
[INFO] Finished at: 2019-04-09T17:51:47+08:00
[INFO] Final Memory: 231M/950M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.2:compile (scala-compile-first) on project streamingpro-mlsql-spark_2.3: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
```

**Comment by allwefantasy** [comment]
it  works fine with you commands:

```
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/target/streamingpro-mlsql-spark_2.3-1.2.0-SNAPSHOT.jar with /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/target/streamingpro-mlsql-spark_2.3-1.2.0-SNAPSHOT-shaded.jar
[INFO] Dependency-reduced POM written at: /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/dependency-reduced-pom.xml
[INFO] Dependency-reduced POM written at: /Users/allwefantasy/CSDNWorkSpace/streamingpro-spark-2.3.x/streamingpro-mlsql/dependency-reduced-pom.xml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] StreamingPro Parent POM ............................ SUCCESS [  1.969 s]
[INFO] streamingpro-jython ................................ SUCCESS [  4.017 s]
[INFO] streamingpro-common ................................ SUCCESS [ 11.652 s]
[INFO] streamingpro-spark-common .......................... SUCCESS [ 17.640 s]
[INFO] streamingpro-api ................................... SUCCESS [  9.036 s]
[INFO] streamingpro-spark-2.3.0-adaptor ................... SUCCESS [ 16.606 s]
[INFO] streamingpro-dsl ................................... SUCCESS [  4.675 s]
[INFO] streamingpro-crawler ............................... SUCCESS [ 16.103 s]
[INFO] streamingpro-xgboost ............................... SUCCESS [  7.606 s]
[INFO] streamingpro-mlsql-spark_2.3 ....................... SUCCESS [01:20 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:51 min
[INFO] Finished at: 2019-04-12T14:17:38+08:00
[INFO] Final Memory: 299M/1084M
[INFO] ------------------------------------------------------------------------
[w@me streamingpro-spark-2.3.x]$
```

Can you  pull the updates and try again?
